# Netlify configuration file

# Build settings
[build]
  command = "npm run build"
  publish = "dist"

# Form handling configuration
[forms]
  # This section configures the form with the name "contact"
  [forms.contact]
    # Sends an email notification for each submission to this address
    notification_email = ["info@magicalhandsmsa.com"]
